apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: ff2u
  description: FF2U warehouse management API for attachments, tasks, bin locations, QR codes, and break pallets.
spec:
  type: openapi
  lifecycle: production
  owner: CNCF
  definition:
    $text: https://raw.githubusercontent.com/backstage/backstage/master/FF2U.openapi.yaml
